language: python

python:
    - 2.7
    - 3.3
    - 3.4
    - pypy

# Commands for install
install:
    - "pip install ."
    - pip install pytest
    - pip install pytest-cov
    - pip install six
    - pip install django
    - pip install django-bootstrap
    - pip install django-bootstrap-toolkit
    - pip install django_tables2
    - pip install django-tinymce
    - pip install coveralls
# Commands for running
script:
    - coverage run --source bootstrap_span -m py.test
# Reporting on coverage
after_success:
    - coveralls

